### ISSUE TITLE
Upload fails with 'NameError uninitialized constant Rex::Post::MetaSSH::Extensions::Stdapi::Net::SFTP'

### ISSUE THREAD

**Issue by sempervictus** [dirtyfilthy/metassh#5]
Trace below, issue occurs when attempting to upload a file via an established meta_ssh session.

[-] Error running command upload: NameError uninitialized constant Rex::Post::MetaSSH::Extensions::Stdapi::Net::SFTP
 /opt/metasploit4/msf4/lib/active_support/dependencies.rb:429:in `rescue in load_missing_constant'
/opt/metasploit4/msf4/lib/active_support/dependencies.rb:425:in`load_missing_constant'
/opt/metasploit4/msf4/lib/active_support/dependencies.rb:80:in `const_missing_with_dependencies'
/home/guinea_pig/.msf4/plugins/meta_ssh/lib/rex/post/meta_ssh/extensions/stdapi/fs/file.rb:172:in`rescue in initialize'
/home/guinea_pig/.msf4/plugins/meta_ssh/lib/rex/post/meta_ssh/extensions/stdapi/fs/file.rb:170:in `initialize'
/home/guinea_pig/.msf4/plugins/meta_ssh/lib/rex/post/meta_ssh/extensions/stdapi/fs/file.rb:103:in`new'
/home/guinea_pig/.msf4/plugins/meta_ssh/lib/rex/post/meta_ssh/extensions/stdapi/fs/file.rb:103:in `upload_file'
/home/guinea_pig/.msf4/plugins/meta_ssh/lib/rex/post/meta_ssh/extensions/stdapi/fs/file.rb:92:in`block in upload'
/home/guinea_pig/.msf4/plugins/meta_ssh/lib/rex/post/meta_ssh/extensions/stdapi/fs/file.rb:84:in `each'
/home/guinea_pig/.msf4/plugins/meta_ssh/lib/rex/post/meta_ssh/extensions/stdapi/fs/file.rb:84:in`upload'
/home/guinea_pig/.msf4/plugins/meta_ssh/lib/rex/post/meta_ssh/ui/console/command_dispatcher/stdapi/fs.rb:452:in `block in cmd_upload'
/home/guinea_pig/.msf4/plugins/meta_ssh/lib/rex/post/meta_ssh/ui/console/command_dispatcher/stdapi/fs.rb:443:in`each'
/home/guinea_pig/.msf4/plugins/meta_ssh/lib/rex/post/meta_ssh/ui/console/command_dispatcher/stdapi/fs.rb:443:in `cmd_upload'
/opt/metasploit4/msf4/lib/rex/ui/text/dispatcher_shell.rb:380:in`run_command'
/home/guinea_pig/.msf4/plugins/meta_ssh/lib/rex/post/meta_ssh/ui/console.rb:99:in `run_command'
/opt/metasploit4/msf4/lib/rex/ui/text/dispatcher_shell.rb:342:in`block in run_single'
/opt/metasploit4/msf4/lib/rex/ui/text/dispatcher_shell.rb:336:in `each'
/opt/metasploit4/msf4/lib/rex/ui/text/dispatcher_shell.rb:336:in`run_single'
/home/guinea_pig/.msf4/plugins/meta_ssh/lib/rex/post/meta_ssh/ui/console.rb:63:in `block in interact'
/opt/metasploit4/msf4/lib/rex/ui/text/shell.rb:189:in`call'
/opt/metasploit4/msf4/lib/rex/ui/text/shell.rb:189:in `run'
/home/guinea_pig/.msf4/plugins/meta_ssh/lib/rex/post/meta_ssh/ui/console.rb:61:in`interact'
/home/guinea_pig/.msf4/plugins/meta_ssh/lib/msf/base/sessions/meta_ssh.rb:270:in `_interact'
/opt/metasploit4/msf4/lib/rex/ui/interactive.rb:48:in`interact'
/opt/metasploit4/msf4/lib/msf/ui/console/command_dispatcher/core.rb:1556:in `cmd_sessions'
/opt/metasploit4/msf4/lib/rex/ui/text/dispatcher_shell.rb:380:in`run_command'
/opt/metasploit4/msf4/lib/rex/ui/text/dispatcher_shell.rb:342:in `block in run_single'
/opt/metasploit4/msf4/lib/rex/ui/text/dispatcher_shell.rb:336:in`each'
/opt/metasploit4/msf4/lib/rex/ui/text/dispatcher_shell.rb:336:in `run_single'
/opt/metasploit4/msf4/lib/rex/ui/text/shell.rb:199:in`run'
/usr/local/sbin/msfconsole:135:in `<main>'

**Comment by dirtyfilthy** [comment]
hey there. i fixed a bug with upload but interestingly it wasn't this one... seems to work for me now. can you pull and retest on your side?

**Comment by sempervictus** [comment]
This just gets grand :). Added your repo as upstream, did a pull, and tested on a cisco ASA5510 (closest ssh host). Utter failure when running pwd or shell within a session:

[-] Session manipulation failed: disconnected: Out of context message type 97 (2) ["/opt/metasploit4/msf4/lib/net/ssh/transport/session.rb:202:in `block in poll_message'", "/opt/metasploit4/msf4/lib/net/ssh/transport/session.rb:192:in`loop'", "/opt/metasploit4/msf4/lib/net/ssh/transport/session.rb:192:in `poll_message'", "/opt/metasploit4/msf4/lib/net/ssh/connection/session.rb:453:in`dispatch_incoming_packets'", "/opt/metasploit4/msf4/lib/net/ssh/connection/session.rb:215:in `preprocess'", "/opt/metasploit4/msf4/lib/net/ssh/connection/session.rb:199:in`process'", "/opt/metasploit4/msf4/lib/net/ssh/connection/session.rb:163:in `block in loop'", "/opt/metasploit4/msf4/lib/net/ssh/connection/session.rb:163:in`loop'", "/opt/metasploit4/msf4/lib/net/ssh/connection/session.rb:163:in `loop'", "/opt/metasploit4/msf4/lib/net/ssh/connection/session.rb:112:in`close'", "/home/test_user/.msf4/plugins/meta_ssh/lib/rex/post/meta_ssh/client.rb:83:in `cleanup_ssh'", "/home/test_user/.msf4/plugins/meta_ssh/lib/msf/base/sessions/meta_ssh.rb:149:in`cleanup'", "/opt/metasploit4/msf4/lib/msf/core/session_manager.rb:267:in `deregister'", "/opt/metasploit4/msf4/lib/msf/core/session/interactive.rb:139:in`_interact_complete'", "/opt/metasploit4/msf4/lib/rex/ui/interactive.rb:71:in `interact'", "/opt/metasploit4/msf4/lib/msf/ui/console/command_dispatcher/core.rb:1556:in`cmd_sessions'", "/opt/metasploit4/msf4/lib/rex/ui/text/dispatcher_shell.rb:380:in `run_command'", "/opt/metasploit4/msf4/lib/rex/ui/text/dispatcher_shell.rb:342:in`block in run_single'", "/opt/metasploit4/msf4/lib/rex/ui/text/dispatcher_shell.rb:336:in `each'", "/opt/metasploit4/msf4/lib/rex/ui/text/dispatcher_shell.rb:336:in`run_single'", "/opt/metasploit4/msf4/lib/rex/ui/text/shell.rb:199:in `run'", "/usr/local/sbin/msfconsole:135:in`<main>'"]

Ran against ubuntu 11.04 - uploaded an exe with no issues. However, shell command 'rm *.exe' produced the following: 

[-] Error running command rm: NoMethodError undefined method `fs' for nil:NilClass
 /home/test_user/.msf4/plugins/meta_ssh/lib/rex/post/meta_ssh/extensions/stdapi/fs/file.rb:60:in`realpath'
/home/test_user/.msf4/plugins/meta_ssh/lib/rex/post/meta_ssh/extensions/stdapi/fs/file.rb:68:in `rm'
/home/test_user/.msf4/plugins/meta_ssh/lib/rex/post/meta_ssh/ui/console/command_dispatcher/stdapi/fs.rb:189:in`cmd_rm'
/opt/metasploit4/msf4/lib/rex/ui/text/dispatcher_shell.rb:380:in `run_command'
/home/test_user/.msf4/plugins/meta_ssh/lib/rex/post/meta_ssh/ui/console.rb:99:in`run_command'
/opt/metasploit4/msf4/lib/rex/ui/text/dispatcher_shell.rb:342:in `block in run_single'
/opt/metasploit4/msf4/lib/rex/ui/text/dispatcher_shell.rb:336:in`each'
/opt/metasploit4/msf4/lib/rex/ui/text/dispatcher_shell.rb:336:in `run_single'
/home/test_user/.msf4/plugins/meta_ssh/lib/rex/post/meta_ssh/ui/console.rb:63:in`block in interact'
/opt/metasploit4/msf4/lib/rex/ui/text/shell.rb:189:in `call'
/opt/metasploit4/msf4/lib/rex/ui/text/shell.rb:189:in`run'
/home/test_user/.msf4/plugins/meta_ssh/lib/rex/post/meta_ssh/ui/console.rb:61:in `interact'
/home/test_user/.msf4/plugins/meta_ssh/lib/msf/base/sessions/meta_ssh.rb:270:in`_interact'
/opt/metasploit4/msf4/lib/rex/ui/interactive.rb:48:in `interact'
/opt/metasploit4/msf4/lib/msf/ui/console/command_dispatcher/core.rb:1556:in`cmd_sessions'
/opt/metasploit4/msf4/lib/rex/ui/text/dispatcher_shell.rb:380:in `run_command'
/opt/metasploit4/msf4/lib/rex/ui/text/dispatcher_shell.rb:342:in`block in run_single'
/opt/metasploit4/msf4/lib/rex/ui/text/dispatcher_shell.rb:336:in `each'
/opt/metasploit4/msf4/lib/rex/ui/text/dispatcher_shell.rb:336:in`run_single'
/opt/metasploit4/msf4/lib/rex/ui/text/shell.rb:199:in `run'
/usr/local/sbin/msfconsole:135:in`<main>'

I should have more time to hack away @ metassh at the end of the week. This is a very useful plug-in and if it can get to the point of acceptance into the framework, then modules can be updated for it as well instead of having to write/rewrite modules to work with the plug-in's session type.

**Comment by dirtyfilthy** [comment]
ok i've pushed a commit to fix the rm issue
